version: "3.8"
services:
    mongodb:
        image : mongo
        container_name: mongodb
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ./databases:/data/databases
        ports:
            - 27017:27017
        restart: unless-stopped

    jaeger:
        image: jaegertracing/all-in-one:latest
        environment:
            - COLLECTOR_ZIPKIN_HTTP_PORT=9411
        ports:
            - "6831:6831/udp"
            - "16686:16686"
            - "9411:9411"
