// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: mts/auth_service/v1/auth_service.proto

package auth_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Statuses int32

const (
	Statuses_valid   Statuses = 0
	Statuses_invalid Statuses = 1
	Statuses_expired Statuses = 2
)

// Enum value maps for Statuses.
var (
	Statuses_name = map[int32]string{
		0: "valid",
		1: "invalid",
		2: "expired",
	}
	Statuses_value = map[string]int32{
		"valid":   0,
		"invalid": 1,
		"expired": 2,
	}
)

func (x Statuses) Enum() *Statuses {
	p := new(Statuses)
	*p = x
	return p
}

func (x Statuses) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Statuses) Descriptor() protoreflect.EnumDescriptor {
	return file_mts_auth_service_v1_auth_service_proto_enumTypes[0].Descriptor()
}

func (Statuses) Type() protoreflect.EnumType {
	return &file_mts_auth_service_v1_auth_service_proto_enumTypes[0]
}

func (x Statuses) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Statuses.Descriptor instead.
func (Statuses) EnumDescriptor() ([]byte, []int) {
	return file_mts_auth_service_v1_auth_service_proto_rawDescGZIP(), []int{0}
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mts_auth_service_v1_auth_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mts_auth_service_v1_auth_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_mts_auth_service_v1_auth_service_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Statuses `protobuf:"varint,1,opt,name=status,proto3,enum=mts_project.category_service.v1.Statuses" json:"status,omitempty"`
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mts_auth_service_v1_auth_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mts_auth_service_v1_auth_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_mts_auth_service_v1_auth_service_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateTokenResponse) GetStatus() Statuses {
	if x != nil {
		return x.Status
	}
	return Statuses_valid
}

var File_mts_auth_service_v1_auth_service_proto protoreflect.FileDescriptor

var file_mts_auth_service_v1_auth_service_proto_rawDesc = []byte{
	0x0a, 0x26, 0x6d, 0x74, 0x73, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x6d, 0x74, 0x73, 0x5f, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x2c, 0x0a, 0x14, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x5a, 0x0a, 0x15, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x41, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x29, 0x2e, 0x6d, 0x74, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x2a, 0x2f, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x12,
	0x09, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x69, 0x6e,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x64, 0x10, 0x02, 0x32, 0x88, 0x01, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x79, 0x0a, 0x08, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x35, 0x2e, 0x6d, 0x74, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x36, 0x2e, 0x6d, 0x74, 0x73, 0x5f, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x36,
	0x38, 0x33, 0x34, 0x2f, 0x74, 0x65, 0x61, 0x6d, 0x31, 0x37, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x61,
	0x75, 0x74, 0x68, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_mts_auth_service_v1_auth_service_proto_rawDescOnce sync.Once
	file_mts_auth_service_v1_auth_service_proto_rawDescData = file_mts_auth_service_v1_auth_service_proto_rawDesc
)

func file_mts_auth_service_v1_auth_service_proto_rawDescGZIP() []byte {
	file_mts_auth_service_v1_auth_service_proto_rawDescOnce.Do(func() {
		file_mts_auth_service_v1_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_mts_auth_service_v1_auth_service_proto_rawDescData)
	})
	return file_mts_auth_service_v1_auth_service_proto_rawDescData
}

var file_mts_auth_service_v1_auth_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mts_auth_service_v1_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mts_auth_service_v1_auth_service_proto_goTypes = []interface{}{
	(Statuses)(0),                 // 0: mts_project.category_service.v1.Statuses
	(*ValidateTokenRequest)(nil),  // 1: mts_project.category_service.v1.ValidateTokenRequest
	(*ValidateTokenResponse)(nil), // 2: mts_project.category_service.v1.ValidateTokenResponse
}
var file_mts_auth_service_v1_auth_service_proto_depIdxs = []int32{
	0, // 0: mts_project.category_service.v1.ValidateTokenResponse.status:type_name -> mts_project.category_service.v1.Statuses
	1, // 1: mts_project.category_service.v1.AuthService.Validate:input_type -> mts_project.category_service.v1.ValidateTokenRequest
	2, // 2: mts_project.category_service.v1.AuthService.Validate:output_type -> mts_project.category_service.v1.ValidateTokenResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mts_auth_service_v1_auth_service_proto_init() }
func file_mts_auth_service_v1_auth_service_proto_init() {
	if File_mts_auth_service_v1_auth_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mts_auth_service_v1_auth_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mts_auth_service_v1_auth_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mts_auth_service_v1_auth_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mts_auth_service_v1_auth_service_proto_goTypes,
		DependencyIndexes: file_mts_auth_service_v1_auth_service_proto_depIdxs,
		EnumInfos:         file_mts_auth_service_v1_auth_service_proto_enumTypes,
		MessageInfos:      file_mts_auth_service_v1_auth_service_proto_msgTypes,
	}.Build()
	File_mts_auth_service_v1_auth_service_proto = out.File
	file_mts_auth_service_v1_auth_service_proto_rawDesc = nil
	file_mts_auth_service_v1_auth_service_proto_goTypes = nil
	file_mts_auth_service_v1_auth_service_proto_depIdxs = nil
}
